from os.path import join
import pandas as pd
from snakemake.utils import validate

configfile: 'config/config.yml'
validate(config, "schemas/config.schema.yml")

#load participants.tsv file, and strip off sub- from participant_id column
df = pd.read_table(config['participants_tsv'])
validate(df, 'schemas/participants.schema.yml')

subjects = df.participant_id.to_list() 
subjects = [ s.strip('sub-') for s in subjects ]

#this include is for the bids() function, and 
#and any other global function declarations
include: 'rules/common.smk'

rule all:
    input:
        warped_flo = expand(bids(root='results',suffix='T1w.nii.gz',space='{template}',desc='SyN',subject='{subject}'),subject=subjects,template=config['templates']),
        done = expand(bids(root='results',subject='{subject}',desc='n4',suffix='T1w_fast.done'),subject=subjects)
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.



include: "rules/atlas_reg.smk"
