from os.path import join
import pandas as pd
from snakemake.utils import validate

configfile: 'config/config.yml'
validate(config, "schemas/config.schema.yml")

#load participants.tsv file, and strip off sub- from participant_id column
df = pd.read_table(config['participants_tsv'])
validate(df, 'schemas/participants.schema.yml')

subjects = df.participant_id.to_list() 
subjects = [ s.strip('sub-') for s in subjects ]

#this include is for the bids() function, and 
#and any other global function declarations
include: 'rules/common.smk'

rule all:
    input:
        tsv = expand(bids(root='results',subject='{subject}',suffix='electrodes.tsv',desc='{atlas}',from_='{template}'),
                subject=subjects,atlas=config['atlases'],template=config['templates']),
        reg_vis = expand(bids(root='qc',subject='{subject}',suffix='regqc.png',from_='subject', to='{template}',desc='{desc}'),
                subject=subjects, desc=['rigid','affine','SyN'],template=config['templates']),
        electrode_vis = expand(bids(root='qc',subject='{subject}',suffix='electrodevis.png',desc='{desc}',space='{template}'),
                subject=subjects, desc=['rigid','affine'],template=config['templates']),
        probseg_vis = expand(bids(root='qc',subject='{subject}',suffix='probseg.png',label='{tissue}', from_='{template}'),
                subject=subjects, tissue=config['tissue_labels'],template=config['templates']),
              



include: "rules/atlas_reg.smk"
