from os.path import join
import pandas as pd
from snakemake.utils import validate

configfile: 'config/config.yml'
validate(config, "schemas/config.schema.yml")

#load participants.tsv file, and strip off sub- from participant_id column
df = pd.read_table(config['participants_tsv'])
validate(df, 'schemas/participants.schema.yml')

subjects = df.participant_id.to_list() 
subjects = [ s.strip('sub-') for s in subjects ]

#this include is for the bids() function, and 
#and any other global function declarations
include: 'rules/common.smk'

rule all:
    input:
#        tsv = expand(bids(root='results',subject='{subject}',suffix='electrodes.tsv',atlas='{atlas}',desc='blur{blur}',from_='{template}'),
#                subject=subjects,atlas=config['atlases'],template=config['templates'],blur=config['atlas_blur']),
        reg_vis = expand(bids(root='qc',subject='{subject}',suffix='regqc.png',from_='subject', to='{template}',desc='{desc}'),
                subject=subjects, desc=['affine','SyN'],template=config['template']),
        electrode_vis = expand(bids(root='qc',subject='{subject}',suffix='electrodevis.png',desc='{desc}',space='{template}'),
                subject=subjects, desc=['affine'],template=config['template']),
        probseg_vis = expand(bids(root='qc',subject='{subject}',suffix='probseg.png', desc='atropos3seg'),
                subject=subjects ),
        atlas_vis = expand(bids(root='qc',subject='{subject}',suffix='dseg.png',atlas='{atlas}', from_='{template}'),
                subject=subjects, atlas=config['atlases'],template=config['template']),
        tsv = expand(bids(root='results',subject='{subject}',suffix='electrodes.tsv',atlas='{atlas}',desc='dilated',from_='{template}'),
                subject=subjects, atlas=config['atlases'],template=config['template'])
#        seg = expand(bids(root='results',subject='{subject}',from_='{template}',suffix='dseg.nii.gz',prior='{prior_f}',mrf='000{mrf_f}',desc='atroposk4'),
#                subject=subjects,template=config['templates'],prior_f=[0,25,5],mrf_f=1)
                
        
include: "rules/registration.smk"
include: "rules/segmentation.smk"
include: "rules/electrodes.smk"
include: "rules/visqc.smk"
