singularity:
    neuroglia: /project/6050199/akhanf/singularity/bids-apps/khanlab_neuroglia-core_latest.sif
    ants: /project/6050199/akhanf/singularity/ants-v2.3.1.sif
# use this URI if not on khanlab compute canada:
#    neuroglia: docker://khanlab/neuroglia-core:latest

subject_t1w: /project/6050199/akhanf/cfmm-bids/data/Khan/epi_iEEG/mri/bids_defaced/sub-{subject}/ses-001/anat/sub-{subject}_ses-001_run-01_T1w_defaced.nii.gz

#use this if a particular subject has a custom path
subject_t1w_custom:
    'P029': /project/6050199/akhanf/cfmm-bids/data/Khan/epi_iEEG/mri/bids_defaced/sub-{subject}/ses-001/anat/sub-{subject}_ses-001_acq-FSPGR_run-01_T1w_defaced.nii.gz



template_t1w: resources/tpl-{template}/tpl-{template}_res-01_T1w.nii.gz
template_mask: resources/tpl-{template}/tpl-{template}_res-01_desc-brain_mask.nii.gz 
template_tissue_probseg: resources/tpl-{template}/tpl-{template}_res-01_label-{tissue}_probseg.nii.gz

tissue_labels:
 - GM
 - WM
 - CSF

templates: 
 - MNI152NLin2009cAsym
# - MNI152NLin6Asym



template_atlas_dseg_nii: resources/tpl-{template}/tpl-{template}_res-01_atlas-{atlas}_dseg.nii.gz
template_atlas_dseg_tsv: resources/tpl-{template}/tpl-{template}_res-01_atlas-{atlas}_dseg.tsv

atlases:
 - Cerebra

subject_electrodes: /project/6050199/akhanf/cfmm-bids/data/Khan/epi_iEEG/clinical/deriv/seega_coordinates/sub-{subject}/sub-{subject}_space-native_desc-ieeg_SEEGA.fcsv

#some naming errors in input files:
subject_electrodes_custom: []

ants:
    dim: 3
    random_seed: 42 #requires ants version at least 2.3.1 (includes --random-seed option)
    intensity_opts: '-u 1 -w [0.01,0.99] -z 1'
    linear:
        reg_iterations: '1000x500x250x0'
        shrink_factors: '6x4x2x1'
        smoothing_factors: '4x2x1x0'
    deform:
        shrink_factors: '12x6x4x2x1'  # default in antsMVTC2: 6x4x2x1 
        smoothing_factors: '6x3x2x1x0vox' # default in antsMVTC2: 3x2x1x0 
        reg_iterations: '100x100x70x50x10' # default in antsMVTC2: 100x100x70x20 
        transform_model: 'SyN[0.1,3,0]'
        sim_metric: CC
    shape_update:
        gradient_step: 0.25


participants_tsv: config/participants.tsv
